// <auto-generated> by stubgen: signatures copied from the real VaM/Unity assemblies. Do not edit. </auto-generated>
#pragma warning disable
using System; using System.Collections; using System.Collections.Generic;
namespace UnityEngine.UI {
public partial class Selectable : global::UnityEngine.EventSystems.UIBehaviour {
  public global::UnityEngine.UI.ColorBlock colors { get; set; }
  public global::UnityEngine.UI.Navigation navigation { get; set; }
  public global::UnityEngine.UI.Graphic targetGraphic { get; set; }
  public Selectable() {}
public enum Transition : int {
  None = 0,
  ColorTint = 1,
  SpriteSwap = 2,
  Animation = 3,
}
}
public partial struct ColorBlock {
  public float colorMultiplier { get; set; }
  public global::UnityEngine.Color disabledColor { get; set; }
  public float fadeDuration { get; set; }
  public global::UnityEngine.Color highlightedColor { get; set; }
  public global::UnityEngine.Color normalColor { get; set; }
  public global::UnityEngine.Color pressedColor { get; set; }
}
public partial struct Navigation {
  public global::UnityEngine.UI.Navigation.Mode mode { get; set; }
public enum Mode : int {
  None = 0,
  Horizontal = 1,
  Vertical = 2,
  Automatic = 3,
  Explicit = 4,
}
}
public partial class Button : global::UnityEngine.UI.Selectable {
  public global::UnityEngine.UI.Button.ButtonClickedEvent onClick { get; set; } = new global::UnityEngine.UI.Button.ButtonClickedEvent();
  public Button() {}
public partial class ButtonClickedEvent : global::UnityEngine.Events.UnityEvent {
  public ButtonClickedEvent() {}
}
}
public partial class ScrollRect : global::UnityEngine.EventSystems.UIBehaviour {
  public global::UnityEngine.RectTransform content { get; set; }
  public bool horizontal { get; set; }
  public global::UnityEngine.UI.ScrollRect.MovementType movementType { get; set; }
  public float scrollSensitivity { get; set; }
  public bool vertical { get; set; }
  public float verticalNormalizedPosition { get; set; }
  public global::UnityEngine.RectTransform viewport { get; set; }
  public ScrollRect() {}
public enum MovementType : int {
  Unrestricted = 0,
  Elastic = 1,
  Clamped = 2,
}
public enum ScrollbarVisibility : int {
  Permanent = 0,
  AutoHide = 1,
  AutoHideAndExpandViewport = 2,
}
public partial class ScrollRectEvent : global::UnityEngine.Events.UnityEvent<global::UnityEngine.Vector2> {
  public ScrollRectEvent() {}
}
}
public abstract partial class HorizontalOrVerticalLayoutGroup : global::UnityEngine.UI.LayoutGroup {
  public bool childControlHeight { get; set; }
  public bool childControlWidth { get; set; }
  public bool childForceExpandHeight { get; set; }
  public bool childForceExpandWidth { get; set; }
  public float spacing { get; set; }
  public HorizontalOrVerticalLayoutGroup() {}
}
public abstract partial class LayoutGroup : global::UnityEngine.EventSystems.UIBehaviour {
  public global::UnityEngine.RectOffset padding { get; set; }
  public LayoutGroup() {}
}
public static partial class LayoutUtility {
  public static float GetPreferredHeight(global::UnityEngine.RectTransform rect) { return default; }
}
public partial class GraphicRaycaster : global::UnityEngine.EventSystems.BaseRaycaster {
  public GraphicRaycaster() {}
}
public partial class VerticalLayoutGroup : global::UnityEngine.UI.HorizontalOrVerticalLayoutGroup {
  public VerticalLayoutGroup() {}
}
public partial class Toggle : global::UnityEngine.UI.Selectable {
  public bool isOn { get; set; }
  public global::UnityEngine.UI.Toggle.ToggleEvent onValueChanged;
  public Toggle() {}
public partial class ToggleEvent : global::UnityEngine.Events.UnityEvent<bool> {
  public ToggleEvent() {}
}
}
public partial class Slider : global::UnityEngine.UI.Selectable {
  public global::UnityEngine.UI.Slider.SliderEvent onValueChanged { get; set; } = new global::UnityEngine.UI.Slider.SliderEvent();
  public float value { get; set; }
  public global::UnityEngine.RectTransform fillRect { get; set; }
  public global::UnityEngine.RectTransform handleRect { get; set; }
  public float maxValue { get; set; }
  public float minValue { get; set; }
  public bool wholeNumbers { get; set; }
  public Slider() {}
public partial class SliderEvent : global::UnityEngine.Events.UnityEvent<float> {
  public SliderEvent() {}
}
}
public partial class LayoutElement : global::UnityEngine.EventSystems.UIBehaviour {
  public LayoutElement() {}
}
public partial class RawImage : global::UnityEngine.UI.MaskableGraphic {
  public RawImage() {}
}
public partial class HorizontalLayoutGroup : global::UnityEngine.UI.HorizontalOrVerticalLayoutGroup {
  public HorizontalLayoutGroup() {}
}
public partial class InputField : global::UnityEngine.UI.Selectable {
  public InputField() {}
public enum ContentType : int {
  Standard = 0,
  Autocorrected = 1,
  IntegerNumber = 2,
  DecimalNumber = 3,
  Alphanumeric = 4,
  Name = 5,
  EmailAddress = 6,
  Password = 7,
  Pin = 8,
  Custom = 9,
}
public enum LineType : int {
  SingleLine = 0,
  MultiLineSubmit = 1,
  MultiLineNewline = 2,
}
public partial class SubmitEvent : global::UnityEngine.Events.UnityEvent<string> {
  public SubmitEvent() {}
}
public partial class OnChangeEvent : global::UnityEngine.Events.UnityEvent<string> {
  public OnChangeEvent() {}
}
}
public partial class AspectRatioFitter : global::UnityEngine.EventSystems.UIBehaviour {
  public AspectRatioFitter() {}
public enum AspectMode : int {
  None = 0,
  WidthControlsHeight = 1,
  HeightControlsWidth = 2,
  FitInParent = 3,
  EnvelopeParent = 4,
}
}
public partial class CanvasScaler : global::UnityEngine.EventSystems.UIBehaviour {
  public CanvasScaler() {}
}
public partial class Scrollbar : global::UnityEngine.UI.Selectable {
  public Scrollbar() {}
public enum Direction : int {
  LeftToRight = 0,
  RightToLeft = 1,
  BottomToTop = 2,
  TopToBottom = 3,
}
}
public partial class LayoutRebuilder {
  public LayoutRebuilder() {}
}
public partial class Mask : global::UnityEngine.EventSystems.UIBehaviour {
  public Mask() {}
}
public partial class VertexHelper {
  public VertexHelper() {}
}
public partial interface ICanvasElement {
}
public partial interface ILayoutElement {
}
public partial interface ILayoutGroup {
}
public partial interface ILayoutController {
}
public partial interface ILayoutIgnorer {
}
public partial interface ILayoutSelfController {
}
public partial interface IMaterialModifier {
}
}
namespace UnityEngine.Events {
public partial class UnityEvent : global::UnityEngine.Events.UnityEventBase {
  public void AddListener(global::UnityEngine.Events.UnityAction call) { }
  public void Invoke() { }
  public UnityEvent() {}
}
public delegate void UnityAction();
public delegate void UnityAction<T0>(T0 arg0);
public abstract partial class UnityEvent<T0> : global::UnityEngine.Events.UnityEventBase {
  public void AddListener(global::UnityEngine.Events.UnityAction<T0> call) { }
  public UnityEvent() {}
}
public delegate void UnityAction<T0, T1>(T0 arg0, T1 arg1);
public delegate void UnityAction<T0, T1, T2>(T0 arg0, T1 arg1, T2 arg2);
public abstract partial class UnityEventBase {
  public UnityEventBase() {}
}
}
namespace UnityEngine.EventSystems {
public partial class PointerEventData : global::UnityEngine.EventSystems.BaseEventData {
  public global::UnityEngine.EventSystems.PointerEventData.InputButton button { get; set; }
  public global::UnityEngine.Vector2 position { get; set; }
  public PointerEventData() {}
public enum InputButton : int {
  Left = 0,
  Right = 1,
  Middle = 2,
}
}
public partial class EventSystem : global::UnityEngine.EventSystems.UIBehaviour {
  public static global::UnityEngine.EventSystems.EventSystem current { get; set; } = new global::UnityEngine.EventSystems.EventSystem();
  public EventSystem() {}
}
public partial interface IPointerDownHandler {
}
public partial interface IEventSystemHandler {
}
public partial interface IBeginDragHandler {
}
public partial interface IDragHandler {
}
public partial interface IEndDragHandler {
}
public partial class EventTrigger : global::UnityEngine.MonoBehaviour {
  public EventTrigger() {}
public partial class TriggerEvent : global::UnityEngine.Events.UnityEvent<global::UnityEngine.EventSystems.BaseEventData> {
  public TriggerEvent() {}
}
public partial class Entry {
  public Entry() {}
}
}
public enum EventTriggerType : int {
  PointerEnter = 0,
  PointerExit = 1,
  PointerDown = 2,
  PointerUp = 3,
  PointerClick = 4,
  Drag = 5,
  Drop = 6,
  Scroll = 7,
  UpdateSelected = 8,
  Select = 9,
  Deselect = 10,
  Move = 11,
  InitializePotentialDrag = 12,
  BeginDrag = 13,
  EndDrag = 14,
  Submit = 15,
  Cancel = 16,
}
public partial class BaseEventData : global::UnityEngine.EventSystems.AbstractEventData {
  public BaseEventData() {}
}
public partial interface IPointerEnterHandler {
}
public partial interface IPointerExitHandler {
}
public partial interface IPointerClickHandler {
}
public partial interface IPointerUpHandler {
}
public partial interface IMoveHandler {
}
public partial interface ISelectHandler {
}
public partial interface IDeselectHandler {
}
public partial interface ISubmitHandler {
}
public partial interface IInitializePotentialDragHandler {
}
public partial interface IScrollHandler {
}
public abstract partial class BaseRaycaster : global::UnityEngine.EventSystems.UIBehaviour {
  public BaseRaycaster() {}
}
public partial interface IUpdateSelectedHandler {
}
public partial interface IDropHandler {
}
public partial interface ICancelHandler {
}
public abstract partial class AbstractEventData {
  public AbstractEventData() {}
}
}
public partial class SuperController : global::UnityEngine.MonoBehaviour {
  public void AddCanvas(global::UnityEngine.Canvas c) { }
  public bool freezeAnimation { get; set; }
  public bool isLoading { get; set; }
  public static global::SuperController singleton { get; set; }
  public global::Atom GetAtomByUid(string uid) { return default; }
  public global::System.Collections.Generic.List<global::Atom> GetAtoms() { return new global::System.Collections.Generic.List<global::Atom>(); }
  public global::System.Collections.Generic.List<string> GetAtomUIDs() { return new global::System.Collections.Generic.List<string>(); }
  public global::Atom GetSelectedAtom() { return default; }
  public static void LogError(string err) { }
  public static void LogMessage(string msg) { }
  public void RemoveCanvas(global::UnityEngine.Canvas c) { }
  public void SelectController(global::FreeControllerV3 controller, bool alignView = default, bool alignRotationOnly = default, bool alignUpDown = default, bool openUI = default) { }
  public void ShowMainHUD(bool setAnchors = default, bool forceMonitor = default) { }
  public void ShowMainHUDMonitor() { }
  public global::UnityEngine.UI.Toggle editModeToggle;
  public global::UnityEngine.UI.Toggle freezeAnimationToggle;
  public global::UnityEngine.Transform hiResScreenshotPreview;
  public bool isOpenVR;
  public bool isOVR;
  public global::UnityEngine.Transform loadingIcon;
  public global::UnityEngine.Transform loadingUI;
  public global::UnityEngine.Camera MonitorCenterCamera;
  public global::SuperController.OnAtomAdded onAtomAddedHandlers;
  public global::SuperController.OnAtomRemoved onAtomRemovedHandlers;
  public global::SuperController.OnAtomUIDsChanged onAtomUIDsChangedHandlers;
  public global::SuperController.OnSceneLoaded onSceneLoadedHandlers;
  public global::UnityEngine.Camera OVRCenterCamera;
  public global::UnityEngine.Transform screenshotPreview;
  public global::UnityEngine.Camera ViveCenterCamera;
  public SuperController() {}
public delegate void ScreenShotCallback(string imgPath);
public delegate void OnAtomUIDsChanged(global::System.Collections.Generic.List<string> atomUIDs);
public delegate void OnAtomUIDRename(string oldName, string newName);
public delegate void OnAtomAdded(global::Atom atom);
public delegate void OnAtomRemoved(global::Atom atom);
public delegate void OnSceneLoaded();
}
public partial class Atom : global::JSONStorable {
  public bool collisionEnabled { get; set; }
  public global::FreeControllerV3[] freeControllers { get; set; }
  public bool on { get; set; }
  public global::UnityEngine.Rigidbody[] rigidbodies { get; set; }
  public string uid { get; set; }
  public global::JSONStorable GetStorableByID(string storeid) { return default; }
  public global::System.Collections.Generic.List<string> GetStorableIDs() { return new global::System.Collections.Generic.List<string>(); }
  public bool RegisterAdditionalStorable(global::JSONStorable js) { return default; }
  public void UnregisterAdditionalStorable(global::JSONStorable js) { }
  public bool destroyed;
  public global::FreeControllerV3 mainController;
  public global::UnityEngine.Transform reParentObject;
  public string type;
  public Atom() {}
}
public partial class MVRPluginManager : global::JSONStorable {
  public global::MVRPlugin CreatePlugin() { return default; }
  public void RemovePluginWithUID(string uid) { }
  public global::UnityEngine.Transform configurableButtonPrefab;
  public global::UnityEngine.Transform configurableColorPickerPrefab;
  public global::UnityEngine.Transform configurableFilterablePopupPrefab;
  public global::UnityEngine.Transform configurablePopupPrefab;
  public global::UnityEngine.Transform configurableScrollablePopupPrefab;
  public global::UnityEngine.Transform configurableSliderPrefab;
  public global::UnityEngine.Transform configurableSpacerPrefab;
  public global::UnityEngine.Transform configurableTextFieldPrefab;
  public global::UnityEngine.Transform configurableTogglePrefab;
  public global::UnityEngine.Transform pluginContainer;
  public global::UnityEngine.RectTransform scriptUIParent;
  public global::UnityEngine.Transform scriptUIPrefab;
  public MVRPluginManager() {}
}
public partial class JSONStorable : global::UnityEngine.MonoBehaviour {
  public virtual void CallAction(string actionName) { }
  public string storeId { get; set; }
  public global::JSONStorableAction GetAction(string name) { return default; }
  public global::JSONStorableBool GetBoolJSONParam(string name) { return default; }
  public global::JSONStorableFloat GetFloatJSONParam(string name) { return default; }
  public virtual global::SimpleJSON.JSONClass GetJSON(bool includePhysical = default, bool includeAppearance = default, bool forceStore = default) { return default; }
  public global::JSONStorableStringChooser GetStringChooserJSONParam(string name) { return default; }
  public global::JSONStorableString GetStringJSONParam(string name) { return default; }
  public global::System.Collections.Generic.List<string> GetStringParamNames() { return new global::System.Collections.Generic.List<string>(); }
  public virtual void InitUI() { }
  public virtual void LateRestoreFromJSON(global::SimpleJSON.JSONClass jc, bool restorePhysical = default, bool restoreAppearance = default, bool setMissingToDefault = default) { }
  public void RegisterAction(global::JSONStorableAction action) { }
  public void RegisterBool(global::JSONStorableBool param) { }
  public void RegisterFloat(global::JSONStorableFloat param) { }
  public void RegisterStringChooser(global::JSONStorableStringChooser param) { }
  public virtual void RestoreFromJSON(global::SimpleJSON.JSONClass jc, bool restorePhysical = default, bool restoreAppearance = default, global::SimpleJSON.JSONArray presetAtoms = default, bool setMissingToDefault = default) { }
  public virtual void SetBoolParamValue(string param, bool value) { }
  public virtual void SetFloatParamValue(string param, float value) { }
  public virtual void SetStringChooserParamValue(string param, string value) { }
  public global::Atom containingAtom;
  public bool exclude;
  public bool onlyStoreIfActive;
  public string overrideId;
  public global::UnityEngine.Transform UITransform;
  public JSONStorable() {}
}
public partial class MVRScript : global::JSONStorable {
  public MVRScript() {}
  public global::UIDynamicButton CreateButton(string label, bool rightSide = default) { return default; }
  public global::UIDynamicPopup CreatePopup(global::JSONStorableStringChooser jsc, bool rightSide = default) { return default; }
  public global::UIDynamicSlider CreateSlider(global::JSONStorableFloat jsf, bool rightSide = default) { return default; }
  public global::UIDynamicTextField CreateTextField(global::JSONStorableString jss, bool rightSide = default) { return default; }
  public global::UIDynamicToggle CreateToggle(global::JSONStorableBool jsb, bool rightSide = default) { return default; }
  public void ForceAwake() { }
  public virtual void Init() { }
  public global::MVRPluginManager manager;
  public global::JSONStorableString pluginLabelJSON;
}
public partial class DAZPhysicsMeshSoftVerticesGroup {
  public float jointDamperNormal { get; set; }
  public float jointSpringNormal { get; set; }
  public global::System.Collections.Generic.List<global::DAZPhysicsMeshSoftVerticesSet> softVerticesSets { get; set; }
  public string name;
  public DAZPhysicsMeshSoftVerticesGroup() {}
}
public partial class DAZPhysicsMesh : global::PhysicsSimulatorJSONStorable {
  public global::System.Collections.Generic.List<global::DAZPhysicsMeshColliderGroup> colliderGroups { get; set; }
  public global::DAZSkinV2 skin { get; set; }
  public global::System.Collections.Generic.List<global::DAZPhysicsMeshSoftVerticesGroup> softVerticesGroups { get; set; }
  public DAZPhysicsMesh() {}
}
public partial class MVRScriptUI : global::UIProvider {
  public global::UnityEngine.UI.Button closeButton;
  public MVRScriptUI() {}
}
public partial class MVRScriptControllerUI : global::UIProvider {
  public global::UnityEngine.UI.Text label;
  public global::UnityEngine.UI.Button openUIButton;
  public MVRScriptControllerUI() {}
}
public partial class UITabSelector : global::UnityEngine.MonoBehaviour {
  public void SetActiveTab(string name) { }
  public UITabSelector() {}
}
public partial class FreeControllerV3 : global::PhysicsSimulatorJSONStorable {
  public bool globalCollisionEnabled { get; set; }
  public FreeControllerV3() {}
public enum PositionState : int {
  On = 0,
  Off = 1,
  Following = 2,
  Hold = 3,
  Lock = 4,
  ParentLink = 5,
  PhysicsLink = 6,
  Comply = 7,
}
public enum RotationState : int {
  On = 0,
  Off = 1,
  Following = 2,
  Hold = 3,
  Lock = 4,
  LookAt = 5,
  ParentLink = 6,
  PhysicsLink = 7,
  Comply = 8,
}
}
public partial class DAZCharacter : global::JSONStorableDynamic {
  public global::DAZSkinV2 skin { get; set; }
  public bool isMale;
  public DAZCharacter() {}
}
public static partial class IEnumerableExtension {
  public static global::System.Collections.Generic.List<T> ToList<T>(global::System.Collections.Generic.IEnumerable<T> collection) { return new global::System.Collections.Generic.List<T>(); }
}
public partial class JSONStorableFloat : global::JSONStorableParam {
  public JSONStorableFloat(string paramName, float startingValue, global::JSONStorableFloat.SetJSONFloatCallback callback, float minValue, float maxValue, bool constrain = default, bool interactable = default) {}
  public JSONStorableFloat(string paramName, float startingValue, float minValue, float maxValue, bool constrain = default, bool interactable = default) {}
  public float val { get; set; }
  public JSONStorableFloat() {}
public delegate void SetJSONFloatCallback(global::JSONStorableFloat jf);
public delegate void SetFloatCallback(float val);
}
public partial class JSONStorableString : global::JSONStorableParam {
  public JSONStorableString(string paramName, string startingValue) {}
  public string val { get; set; }
  public JSONStorableString() {}
public delegate void SetStringCallback(string val);
}
public partial class DAZCharacterSelector : global::JSONStorable {
  public global::DAZCharacterSelector.Gender gender { get; set; }
  public global::DAZCharacter selectedCharacter { get; set; }
  public global::DAZClothingItem GetClothingItem(string itemId) { return default; }
  public bool RefreshRuntimeMorphs() { return default; }
  public DAZCharacterSelector() {}
public enum Gender : int {
  None = 0,
  Male = 1,
  Female = 2,
  Both = 3,
}
}
public partial class DAZSkinV2 : global::GPUTools.Skinner.Scripts.Providers.PreCalcMeshProvider {
  public void FlushBuffers() { }
  public bool useSmoothing { get; set; }
  public bool wasInit { get; set; }
  public global::DAZMesh dazMesh;
  public global::UnityEngine.Vector3 drawOffset;
  public global::UnityEngine.Material[] GPUmaterials;
  public bool[] materialsEnabled;
  public global::UnityEngine.Vector3[] rawSkinnedVerts;
  public global::UnityEngine.ComputeBuffer rawVertsBuffer;
  public global::DAZSkinV2.SkinMethod skinMethod;
  public global::UnityEngine.ComputeBuffer smoothedVertsBuffer;
  public global::DAZBone[] strongestDAZBone;
  public DAZSkinV2() {}
public enum SkinMethod : int {
  CPU = 0,
  GPU = 1,
  CPUAndGPU = 2,
}
}
public partial class DAZMesh : global::MVR.ObjectAllocator {
  public string[] materialNames { get; set; }
  public int numBaseVertices { get; set; }
  public global::UnityEngine.Vector2[] UV { get; set; }
  public global::UnityEngine.Mesh uvMappedMesh { get; set; }
  public int[] UVTriangles { get; set; }
  public global::System.Collections.Generic.Dictionary<int, int> uvVertToBaseVert { get; set; }
  public bool wasInit { get; set; }
  public global::UnityEngine.Material[] materials;
  public DAZMesh() {}
}
public partial class AutoCollider : global::PhysicsSimulator {
  public bool createSoftCollider { get; set; }
  public global::DAZSkinV2 skin { get; set; }
  public global::UnityEngine.Collider hardCollider;
  public global::UnityEngine.Collider jointCollider;
  public int targetVertex;
  public AutoCollider() {}
}
public partial class DAZPhysicsMeshSoftVerticesSet {
  public global::UnityEngine.Collider jointCollider;
  public global::UnityEngine.Collider jointCollider2;
  public int targetVertex;
  public DAZPhysicsMeshSoftVerticesSet() {}
}
public partial class DAZPhysicsMeshColliderGroup {
  public global::DAZPhysicsMeshCapsuleCollider[] colliders;
  public DAZPhysicsMeshColliderGroup() {}
}
public partial class DAZPhysicsMeshCapsuleCollider {
  public global::UnityEngine.CapsuleCollider collider;
  public int frontVertex;
  public DAZPhysicsMeshCapsuleCollider() {}
}
public partial class DAZBone : global::JSONStorable {
  public DAZBone() {}
}
public partial class DAZClothingItem : global::DAZDynamicItem {
  public DAZClothingItem() {}
}
public partial class DAZHairGroup : global::DAZDynamicItem {
  public DAZHairGroup() {}
}
public partial class MVRPlugin {
  public global::JSONStorableUrl pluginURLJSON;
  public string uid;
  public MVRPlugin() {}
}
public partial class JSONStorableBool : global::JSONStorableParam {
  public JSONStorableBool(string paramName, bool startingValue) {}
  public bool val { get; set; }
  public JSONStorableBool() {}
public delegate void SetBoolCallback(bool val);
public delegate void SetJSONBoolCallback(global::JSONStorableBool jb);
}
public partial class JSONStorableUrl : global::JSONStorableString {
  public JSONStorableUrl() {}
}
public partial class JSONStorableAction {
  public JSONStorableAction(string n, global::JSONStorableAction.ActionCallback callback) {}
  public JSONStorableAction() {}
public delegate void ActionCallback();
}
public partial class JSONStorableStringChooser : global::JSONStorableParam {
  public JSONStorableStringChooser(string paramName, global::System.Collections.Generic.List<string> choicesList, string startingValue, string displayName, global::JSONStorableStringChooser.SetStringCallback callback) {}
  public string val { get; set; }
  public JSONStorableStringChooser() {}
public delegate void PopupOpenCallback();
public delegate void SetStringCallback(string val);
public delegate void SetJSONStringCallback(global::JSONStorableStringChooser js);
}
public partial class UIDynamicButton : global::UIDynamic {
  public global::UnityEngine.UI.Button button;
  public UIDynamicButton() {}
}
public partial class UIDynamicToggle : global::UIDynamic {
  public global::UnityEngine.UI.Toggle toggle;
  public UIDynamicToggle() {}
}
public partial class UserPreferences : global::UnityEngine.MonoBehaviour {
  public global::UserPreferences.GlowEffectsLevel glowEffects { get; set; }
  public bool mirrorReflections { get; set; }
  public int msaaLevel { get; set; }
  public bool physicsHighQuality { get; set; }
  public global::UserPreferences.PhysicsRate physicsRate { get; set; }
  public int physicsUpdateCap { get; set; }
  public int pixelLightCount { get; set; }
  public bool realtimeReflectionProbes { get; set; }
  public float renderScale { get; set; }
  public global::UserPreferences.ShaderLOD shaderLOD { get; set; }
  public int smoothPasses { get; set; }
  public bool softPhysics { get; set; }
  public void SetPhysicsRateFromString(string pr) { }
  public static global::UserPreferences singleton;
  public UserPreferences() {}
public enum ShaderLOD : int {
  Low = 250,
  Medium = 400,
  High = 600,
}
public enum GlowEffectsLevel : int {
  Off = 0,
  Low = 1,
  High = 2,
}
public enum PhysicsRate : int {
  Auto = 0,
  _45 = 1,
  _60 = 2,
  _72 = 3,
  _80 = 4,
  _90 = 5,
  _120 = 6,
  _144 = 7,
  _240 = 8,
  _288 = 9,
}
}
public partial class UIDynamicSlider : global::UIDynamic {
  public void ConfigureQuickButtons(float m1v, float m2v, float m3v, float m4v, float p1v, float p2v, float p3v, float p4v) { }
  public bool autoSetQuickButtons { get; set; }
  public bool quickButtonsEnabled { get; set; }
  public bool rangeAdjustEnabled { get; set; }
  public string valueFormat { get; set; }
  public global::UnityEngine.UI.Slider slider;
  public UIDynamicSlider() {}
}
public partial class UIDynamic : global::UnityEngine.MonoBehaviour {
  public float height { get; set; }
  public UIDynamic() {}
}
public partial class HairSimControl : global::PhysicsSimulatorJSONStorable {
  public HairSimControl() {}
}
public partial class ClothSimControl : global::PhysicsSimulatorJSONStorable {
  public ClothSimControl() {}
}
public partial class UIDynamicPopup : global::UIDynamic {
  public UIDynamicPopup() {}
}
public partial class UIDynamicTextField : global::UIDynamic {
  public UIDynamicTextField() {}
}
public partial class DAZDynamicItem : global::JSONStorableDynamic {
  public string[] tagsArray { get; set; }
  public string displayName;
  public DAZDynamicItem() {}
}
public partial class DAZCharacterMaterialOptions : global::MaterialOptions {
  public global::DAZSkinV2 skin { get; set; }
  public DAZCharacterMaterialOptions() {}
}
public partial class MaterialOptions : global::JSONStorable {
  public MaterialOptions() {}
  public virtual void SetAllParameters() { }
  public virtual void SetTextureGroupSet(global::MaterialOptionTextureGroup tg, string setName, int onlyTextureNumber = default, global::UnityEngine.Texture customTexture = default, bool allowNull = default) { }
  public string currentTextureGroup1Set;
  public global::UnityEngine.Texture2D customTexture4;
  public bool customTexture4IsNull;
  public global::UnityEngine.Transform materialContainer;
  public global::UnityEngine.Material materialForDefaults;
  public int[] paramMaterialSlots;
  public global::UnityEngine.Renderer[] renderers;
  public global::MaterialOptionTextureGroup textureGroup1;
}
public partial class MaterialOptionTextureGroup {
  public MaterialOptionTextureGroup() {}
  public int[] materialSlots;
}
public partial class DAZMergedSkinV2 : global::DAZSkinV2 {
  public DAZMergedSkinV2() {}
}
public partial class GenerateDAZMorphsControlUI : global::GenerateTabbedUI {
  public GenerateDAZMorphsControlUI() {}
}
public partial class JSONStorableColor : global::JSONStorableParam {
  public JSONStorableColor() {}
public delegate void SetHSVColorCallback(float h, float s, float v);
}
public partial struct HSVColor {
}
public partial class DAZMorph {
  public DAZMorph() {}
}
public partial class UIDynamicColorPicker : global::UIDynamic {
  public UIDynamicColorPicker() {}
}
public abstract partial class JSONStorableParam {
  public JSONStorableParam() {}
public enum StoreType : int {
  Appearance = 0,
  Physical = 1,
  Any = 2,
  Full = 3,
}
}
public partial class HSVColorPicker : global::TwoDPicker {
  public HSVColorPicker() {}
}
public partial class UIPopup : global::UnityEngine.MonoBehaviour {
  public UIPopup() {}
public delegate void OnOpenPopup();
}
public partial class NamedAudioClip {
  public NamedAudioClip() {}
}
public partial class AudioClipManager : global::JSONStorable {
  public AudioClipManager() {}
}
public partial class Trigger {
  public Trigger() {}
}
public partial interface TriggerHandler {
}
public partial class TriggerActionDiscrete : global::TriggerAction {
  public TriggerActionDiscrete() {}
}
public partial class TriggerActionTransition : global::TriggerAction {
  public TriggerActionTransition() {}
}
public partial class TriggerActionTransitionUI : global::TriggerActionUI {
  public TriggerActionTransitionUI() {}
}
public partial class ImageLoaderThreaded : global::UnityEngine.MonoBehaviour {
  public ImageLoaderThreaded() {}
public delegate void ImageLoaderCallback(global::ImageLoaderThreaded.QueuedImage qi);
public partial class QueuedImage {
  public QueuedImage() {}
}
}
public partial class LineDrawer {
  public LineDrawer() {}
}
public partial class PhysicsSimulatorJSONStorable : global::ScaleChangeReceiverJSONStorable {
  public PhysicsSimulatorJSONStorable() {}
}
public partial class UIProvider : global::UnityEngine.MonoBehaviour {
  public UIProvider() {}
}
public partial class JSONStorableDynamic : global::UnityEngine.MonoBehaviour {
  public JSONStorableDynamic() {}
}
public partial interface RenderSuspend {
}
public partial class PhysicsSimulator : global::ScaleChangeReceiver {
  public PhysicsSimulator() {}
}
public partial class GenerateTabbedUI : global::UnityEngine.MonoBehaviour {
  public GenerateTabbedUI() {}
}
public partial class TwoDPicker : global::UnityEngine.MonoBehaviour {
  public TwoDPicker() {}
}
public partial interface TriggerActionHandler {
}
public abstract partial class TriggerAction {
  public TriggerAction() {}
}
public partial class TriggerActionUI : global::UIProvider {
  public TriggerActionUI() {}
}
public partial class ScaleChangeReceiverJSONStorable : global::JSONStorable {
  public ScaleChangeReceiverJSONStorable() {}
}
public partial class ScaleChangeReceiver : global::UnityEngine.MonoBehaviour {
  public ScaleChangeReceiver() {}
}
namespace UnityEngine {
public sealed partial class Rigidbody : global::UnityEngine.Component {
  public void AddForce(global::UnityEngine.Vector3 force, global::UnityEngine.ForceMode mode) { }
  public bool detectCollisions { get; set; }
  public bool isKinematic { get; set; }
  public float mass { get; set; }
  public global::UnityEngine.Vector3 position { get; set; }
  public global::UnityEngine.Vector3 worldCenterOfMass { get; set; }
  public global::UnityEngine.Vector3 GetPointVelocity(global::UnityEngine.Vector3 worldPoint) { return default; }
  public Rigidbody() {}
}
public partial class Collider : global::UnityEngine.Component {
  public global::UnityEngine.Rigidbody attachedRigidbody { get; set; }
  public global::UnityEngine.Bounds bounds { get; set; }
  public bool enabled { get; set; }
  public bool isTrigger { get; set; }
  public global::UnityEngine.PhysicMaterial sharedMaterial { get; set; }
  public Collider() {}
}
public enum ForceMode : int {
  Force = 0,
  Acceleration = 5,
  Impulse = 1,
  VelocityChange = 2,
}
public partial class Collision {
  public global::UnityEngine.Collider collider { get; set; }
  public global::UnityEngine.ContactPoint[] contacts { get; set; }
  public global::UnityEngine.Vector3 impulse { get; set; }
  public global::UnityEngine.Vector3 relativeVelocity { get; set; }
  public global::UnityEngine.Rigidbody rigidbody { get; set; }
  public Collision() {}
}
public partial struct ContactPoint {
  public global::UnityEngine.Vector3 normal { get; set; }
  public global::UnityEngine.Vector3 point { get; set; }
  public global::UnityEngine.Collider thisCollider { get; set; }
}
public sealed partial class PhysicMaterial : global::UnityEngine.Object {
  public float dynamicFriction { get; set; }
  public global::UnityEngine.PhysicMaterialCombine frictionCombine { get; set; }
  public PhysicMaterial() {}
}
public sealed partial class SphereCollider : global::UnityEngine.Collider {
  public float radius { get; set; }
  public SphereCollider() {}
}
public sealed partial class CapsuleCollider : global::UnityEngine.Collider {
  public int direction { get; set; }
  public float radius { get; set; }
  public CapsuleCollider() {}
}
public partial struct Bounds {
  public global::UnityEngine.Vector3 center { get; set; }
  public global::UnityEngine.Vector3 extents { get; set; }
}
public sealed partial class AssetBundle : global::UnityEngine.Object {
  public T LoadAsset<T>(string name) { return default; }
  public static global::UnityEngine.AssetBundle LoadFromMemory(byte[] binary) { return default; }
  public void Unload(bool unloadAllLoadedObjects) { }
  public AssetBundle() {}
}
public sealed partial class Shader : global::UnityEngine.Object {
  public static global::UnityEngine.Shader Find(string name) { return default; }
  public bool isSupported { get; set; }
  public Shader() {}
}
public partial class Material : global::UnityEngine.Object {
  public Material(global::UnityEngine.Shader shader) {}
  public Material(global::UnityEngine.Material source) {}
  public global::UnityEngine.Texture GetTexture(string name) { return default; }
  public global::UnityEngine.Vector2 GetTextureOffset(string name) { return default; }
  public global::UnityEngine.Vector2 GetTextureScale(string name) { return default; }
  public bool HasProperty(string name) { return default; }
  public global::UnityEngine.Shader shader { get; set; }
  public void SetFloat(string name, float value) { }
  public bool SetPass(int pass) { return default; }
  public void SetTexture(string name, global::UnityEngine.Texture value) { }
  public void SetTextureOffset(string name, global::UnityEngine.Vector2 value) { }
  public void SetTextureScale(string name, global::UnityEngine.Vector2 value) { }
  public void SetVector(string name, global::UnityEngine.Vector4 value) { }
  public Material() {}
}
public partial class RenderTexture : global::UnityEngine.Texture {
  public RenderTexture(int width, int height, int depth, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite) {}
  public bool Create() { return default; }
  public void GenerateMips() { }
  public static global::UnityEngine.RenderTexture active { get; set; }
  public void Release() { }
  public bool autoGenerateMips { get; set; }
  public bool useMipMap { get; set; }
  public RenderTexture() {}
}
public partial struct Color32 {
  public Color32(byte r, byte g, byte b, byte a) {}
  public byte a;
  public byte b;
  public byte g;
  public byte r;
}
public sealed partial class GL {
  public static void Begin(int mode) { }
  public static void Color(global::UnityEngine.Color c) { }
  public static void End() { }
  public static bool sRGBWrite { get; set; }
  public static void LoadOrtho() { }
  public static void PopMatrix() { }
  public static void PushMatrix() { }
  public static void TexCoord2(float x, float y) { }
  public static void Vertex3(float x, float y, float z) { }
  public GL() {}
}
public sealed partial class QualitySettings : global::UnityEngine.Object {
  public static global::UnityEngine.ColorSpace activeColorSpace { get; set; }
  public QualitySettings() {}
}
public sealed partial class Mesh : global::UnityEngine.Object {
  public int subMeshCount { get; set; }
  public int[] GetTriangles(int submesh) { return new int[0]; }
  public Mesh() {}
}
public sealed partial class ComputeBuffer {
  public int count { get; set; }
  public ComputeBuffer() {}
}
public sealed partial class SystemInfo {
  public static bool supportsAsyncGPUReadback { get; set; }
  public SystemInfo() {}
}
public enum PhysicMaterialCombine : int {
  Average = 0,
  Minimum = 2,
  Multiply = 1,
  Maximum = 3,
}
public enum RenderTextureFormat : int {
  ARGB32 = 0,
  Depth = 1,
  ARGBHalf = 2,
  Shadowmap = 3,
  RGB565 = 4,
  ARGB4444 = 5,
  ARGB1555 = 6,
  Default = 7,
  ARGB2101010 = 8,
  DefaultHDR = 9,
  ARGB64 = 10,
  ARGBFloat = 11,
  RGFloat = 12,
  RGHalf = 13,
  RFloat = 14,
  RHalf = 15,
  R8 = 16,
  ARGBInt = 17,
  RGInt = 18,
  RInt = 19,
  BGRA32 = 20,
  RGB111110Float = 22,
  RG32 = 23,
  RGBAUShort = 24,
  RG16 = 25,
  BGRA10101010_XR = 26,
  BGR101010_XR = 27,
}
public enum RenderTextureReadWrite : int {
  Default = 0,
  Linear = 1,
  sRGB = 2,
}
public enum TextureWrapMode : int {
  Repeat = 0,
  Clamp = 1,
  Mirror = 2,
  MirrorOnce = 3,
}
public enum FilterMode : int {
  Point = 0,
  Bilinear = 1,
  Trilinear = 2,
}
public enum ColorSpace : int {
  Uninitialized = -1,
  Gamma = 0,
  Linear = 1,
}
public partial class Renderer : global::UnityEngine.Component {
  public global::UnityEngine.Material[] materials { get; set; }
  public bool enabled { get; set; }
  public global::UnityEngine.Material[] sharedMaterials { get; set; }
  public Renderer() {}
}
public partial struct Ray {
  public Ray(global::UnityEngine.Vector3 origin, global::UnityEngine.Vector3 direction) {}
}
public partial class Physics {
  public static int RaycastNonAlloc(global::UnityEngine.Ray ray, global::UnityEngine.RaycastHit[] results, float maxDistance) { return default; }
  public Physics() {}
}
public partial struct RaycastHit {
  public global::UnityEngine.Collider collider { get; set; }
}
public static partial class ImageConversion {
  public static bool LoadImage(global::UnityEngine.Texture2D tex, byte[] data) { return true; }
}
public sealed partial class AudioSource : global::UnityEngine.AudioBehaviour {
  public void PlayOneShot(global::UnityEngine.AudioClip clip, float volumeScale) { }
  public float dopplerLevel { get; set; }
  public float maxDistance { get; set; }
  public float minDistance { get; set; }
  public float pitch { get; set; }
  public bool playOnAwake { get; set; }
  public float spatialBlend { get; set; }
  public bool spatialize { get; set; }
  public AudioSource() {}
}
public sealed partial class Random {
  public static int Range(int min, int max) { return default; }
  public Random() {}
}
public sealed partial class MeshFilter : global::UnityEngine.Component {
  public global::UnityEngine.Mesh sharedMesh { get; set; }
  public MeshFilter() {}
}
public partial class MeshRenderer : global::UnityEngine.Renderer {
  public MeshRenderer() {}
}
public sealed partial class TextMesh : global::UnityEngine.Component {
  public TextMesh() {}
}
public enum TextAlignment : int {
  Left = 0,
  Center = 1,
  Right = 2,
}
public enum Space : int {
  World = 0,
  Self = 1,
}
public sealed partial class LineRenderer : global::UnityEngine.Renderer {
  public LineRenderer() {}
}
public enum PrimitiveType : int {
  Sphere = 0,
  Capsule = 1,
  Cylinder = 2,
  Cube = 3,
  Plane = 4,
  Quad = 5,
}
public sealed partial class BoxCollider : global::UnityEngine.Collider {
  public BoxCollider() {}
}
public sealed partial class MaterialPropertyBlock {
  public MaterialPropertyBlock() {}
}
public enum SendMessageOptions : int {
  RequireReceiver = 0,
  DontRequireReceiver = 1,
}
public sealed partial class Sprite : global::UnityEngine.Object {
  public Sprite() {}
}
public sealed partial class RectTransformUtility {
  public RectTransformUtility() {}
}
public partial class AsyncOperation : global::UnityEngine.YieldInstruction {
  public AsyncOperation() {}
}
public sealed partial class CanvasGroup : global::UnityEngine.Component {
  public CanvasGroup() {}
}
public sealed partial class CanvasRenderer : global::UnityEngine.Component {
  public CanvasRenderer() {}
}
public sealed partial class TextGenerator {
  public TextGenerator() {}
}
public partial struct UICharInfo {
}
public partial struct UIVertex {
}
public partial interface ISerializationCallbackReceiver {
}
public partial class AudioBehaviour : global::UnityEngine.Behaviour {
  public AudioBehaviour() {}
}
public partial class YieldInstruction {
  public YieldInstruction() {}
}
public partial interface ICanvasRaycastFilter {
}
}
namespace UnityEngine.SceneManagement {
public partial class SceneManager {
  public static void add_sceneLoaded(global::UnityEngine.Events.UnityAction<global::UnityEngine.SceneManagement.Scene, global::UnityEngine.SceneManagement.LoadSceneMode> value) { }
  public static void remove_sceneLoaded(global::UnityEngine.Events.UnityAction<global::UnityEngine.SceneManagement.Scene, global::UnityEngine.SceneManagement.LoadSceneMode> value) { }
  public SceneManager() {}
}
public partial struct Scene {
}
public enum LoadSceneMode : int {
  Single = 0,
  Additive = 1,
}
}
namespace UnityEngine.Experimental.Rendering {
public static partial class AsyncGPUReadback {
  public static global::UnityEngine.Experimental.Rendering.AsyncGPUReadbackRequest Request(global::UnityEngine.ComputeBuffer src, int size, int offset) { return default; }
}
public partial struct AsyncGPUReadbackRequest {
  public bool done { get; set; }
  public bool hasError { get; set; }
  public global::Unity.Collections.NativeArray<T> GetData<T>(int layer = default) { return default; }
}
}
namespace Unity.Collections {
public partial struct NativeArray<T> {
  public void CopyTo(T[] array) { }
}
}
namespace MVR.FileManagement {
public partial class FileManager : global::UnityEngine.MonoBehaviour {
  public static bool FileExists(string path, bool onlySystemFiles = default, bool restrictPath = default) { return default; }
  public FileManager() {}
}
}
namespace MeshVR {
public partial class PresetManager : global::UnityEngine.MonoBehaviour {
  public global::UnityEngine.Events.UnityEvent postLoadEvent;
  public PresetManager() {}
}
public partial class AssetLoader : global::UnityEngine.MonoBehaviour {
  public AssetLoader() {}
public partial class AssetBundleFromFileRequest {
  public AssetBundleFromFileRequest() {}
}
}
public partial class Selector : global::UnityEngine.MonoBehaviour {
  public Selector() {}
}
public partial interface IBinaryStorable {
}
}
namespace SimpleJSON {
public partial class JSONNode {
  public virtual void Add(global::SimpleJSON.JSONNode aItem) { }
  public int Count { get; set; }
  public global::SimpleJSON.JSONNode Item { get; set; }
  public string Value { get; set; }
  public static bool op_Equality(global::SimpleJSON.JSONNode a, object b) { return default; }
  public static bool op_Inequality(global::SimpleJSON.JSONNode a, object b) { return default; }
  public JSONNode() {}
}
public partial class JSONArray : global::SimpleJSON.JSONNode {
  public JSONArray() {}
}
public partial class JSONClass : global::SimpleJSON.JSONNode {
  public JSONClass() {}
  public virtual global::System.Collections.IEnumerator GetEnumerator() { return default; }
  public bool HasKey(string aKey) { return default; }
}
public partial class JSONData : global::SimpleJSON.JSONNode {
  public JSONData(string aData) {}
  public JSONData(bool aData) {}
  public JSONData(float aData) {}
  public JSONData() {}
}
public static partial class JSON {
  public static global::SimpleJSON.JSONNode Parse(string aJSON) { return default; }
}
}
namespace GPUTools.Skinner.Scripts.Providers {
public partial class PreCalcMeshProvider : global::UnityEngine.MonoBehaviour {
  public global::UnityEngine.Mesh Mesh { get; set; }
  public PreCalcMeshProvider() {}
}
}
namespace uFileBrowser {
public partial class FileBrowser : global::UnityEngine.MonoBehaviour {
  public FileBrowser() {}
}
public delegate void FileBrowserCallback(string path);
}
namespace MVR.FileManagementSecure {
public partial class FileManagerSecure {
  public FileManagerSecure() {}
}
}
namespace AssetBundles {
public abstract partial class AssetBundleLoadAssetOperation : global::AssetBundles.AssetBundleLoadOperation {
  public AssetBundleLoadAssetOperation() {}
}
public partial class AssetBundleManager : global::UnityEngine.MonoBehaviour {
  public AssetBundleManager() {}
}
public abstract partial class AssetBundleLoadOperation {
  public AssetBundleLoadOperation() {}
}
}
namespace MVR {
public partial class ObjectAllocator : global::UnityEngine.MonoBehaviour {
  public ObjectAllocator() {}
}
}
namespace GPUTools.Skinner.Scripts.Abstract {
public partial interface IMeshProvider {
}
}
