<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZeroT.IamjoiGarmentsStandalone</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="BepInEx" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(VaMManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(VaMManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\UiKit\RlChrome.cs" Link="UiKit\RlChrome.cs" />
    <Compile Include="..\UiKit\RlExternal.cs" Link="UiKit\RlExternal.cs" />
    <Compile Include="..\UiKit\RlImguiExternal.cs" Link="UiKit\RlImguiExternal.cs" />
  </ItemGroup>
</Project>