<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZeroT.DecalMakerStandalone</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="DecalMaker.var" LogicalName="DecalMaker.var" />
    <Compile Include="..\UiKit\RlUgui.cs" Link="UiKit\RlUgui.cs" />
    <Compile Include="..\UiKit\RlExternal.cs" Link="UiKit\RlExternal.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(VaMManagedDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(VaMManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(VaMManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
