<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KeyGenerator</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="certificates_manifest.txt" />
    <EmbeddedResource Include="certificates_manifest.txt" LogicalName="certificates_manifest.txt" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx" />
  </ItemGroup>
</Project>