using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Mono.Cecil;

// stubgen <out.cs> <shim.dll> <managedDir> <plugin.dll>...
// For every type/member that the plugin DLLs reference in UnityEngine*/Assembly-CSharp/BepInEx but the shim lacks,
// emit a stub (signatures copied from the real game assemblies). Existing shim types are only reported when members are missing.
internal static class Program
{
	private static ModuleDefinition shim;
	private static List<ModuleDefinition> real = new List<ModuleDefinition>();
	private static Dictionary<string, TypeDefinition> realTypes = new Dictionary<string, TypeDefinition>();
	private static HashSet<string> shimTypes = new HashSet<string>();
	private static Dictionary<string, HashSet<string>> shimMembers = new Dictionary<string, HashSet<string>>();
	private static Dictionary<string, Need> needs = new Dictionary<string, Need>();   // by real type full name ('/' nested)
	private static Queue<string> work = new Queue<string>();
	private static List<string> report = new List<string>();

	private class Need
	{
		public TypeDefinition def;
		public bool existsInShim;
		public HashSet<MethodDefinition> methods = new HashSet<MethodDefinition>();
		public HashSet<FieldDefinition> fields = new HashSet<FieldDefinition>();
	}

	private static bool IsGameScope(IMetadataScope s) =>
		s is ModuleDefinition || (s is AssemblyNameReference a && (a.Name.StartsWith("UnityEngine") || a.Name == "Assembly-CSharp" || a.Name == "BepInEx" || a.Name == "0Harmony"));

	private static int Main(string[] args)
	{
		string outFile = args[0]; string shimPath = args[1]; string managed = args[2];
		shim = ModuleDefinition.ReadModule(shimPath);
		foreach (var t in AllTypes(shim.Types)) { shimTypes.Add(t.FullName); var set = new HashSet<string>(); foreach (var m in t.Methods) set.Add(m.Name); foreach (var f in t.Fields) set.Add(f.Name); shimMembers[t.FullName] = set; }
		var resolver = new DefaultAssemblyResolver();
		resolver.AddSearchDirectory(managed);
		resolver.AddSearchDirectory(Path.Combine(Path.GetDirectoryName(managed), "..", "BepInEx", "core"));
		foreach (var f in Directory.GetFiles(managed, "*.dll"))
		{
			string n = Path.GetFileName(f);
			if (!(n.StartsWith("UnityEngine") || n == "Assembly-CSharp.dll")) continue;
			try { var m = ModuleDefinition.ReadModule(f, new ReaderParameters { AssemblyResolver = resolver }); real.Add(m); foreach (var t in AllTypes(m.Types)) if (!realTypes.ContainsKey(t.FullName)) realTypes[t.FullName] = t; } catch { }
		}
		foreach (var plugArg in args.Skip(3))
		{
			bool typesOnly = plugArg.StartsWith("@types:");
			string plug = typesOnly ? plugArg.Substring(7) : plugArg;
			var mod = ModuleDefinition.ReadModule(plug, new ReaderParameters { AssemblyResolver = resolver });
			if (typesOnly) { foreach (var tr0 in mod.GetTypeReferences()) if (IsGameScope(tr0.Scope) && realTypes.TryGetValue(tr0.FullName, out var rd0)) GetNeed(rd0); continue; }
			foreach (var mr in mod.GetMemberReferences())
			{
				if (mr.DeclaringType == null || mr.DeclaringType.IsGenericInstance && !IsGameScope(mr.DeclaringType.GetElementType().Scope)) continue;
				var dt = mr.DeclaringType.GetElementType();
				if (!IsGameScope(dt.Scope)) continue;
				string key = dt.FullName.Replace('/', '+');
				if (!realTypes.TryGetValue(dt.FullName, out var rd)) { report.Add("no real definition for " + dt.FullName); continue; }
				var need = GetNeed(rd);
				if (mr is MethodReference m)
				{
					MethodDefinition md = null; try { md = (m is GenericInstanceMethod gim ? gim.ElementMethod : m).Resolve(); } catch { }
					if (md == null) { report.Add("cannot resolve method " + mr.FullName); continue; }
					need.methods.Add(md);
				}
				else if (mr is FieldReference fr)
				{
					FieldDefinition fd = null; try { fd = fr.Resolve(); } catch { }
					if (fd == null) { report.Add("cannot resolve field " + mr.FullName); continue; }
					need.fields.Add(fd);
				}
			}
			foreach (var tr in mod.GetTypeReferences())
				if (IsGameScope(tr.Scope) && realTypes.TryGetValue(tr.FullName, out var rd2)) GetNeed(rd2);
		}
		// closure over base types and signature types
		while (work.Count > 0)
		{
			var n = needs[work.Dequeue()];
			if (n.def.BaseType != null) Require(n.def.BaseType);
			foreach (var m in n.methods) { Require(m.ReturnType); foreach (var p in m.Parameters) Require(p.ParameterType); }
			foreach (var f in n.fields) Require(f.FieldType);
			if (n.def.DeclaringType != null) GetNeed(n.def.DeclaringType);
			foreach (var i in n.def.Interfaces) Require(i.InterfaceType);
			if (IsDelegate(n.def)) { var inv = n.def.Methods.First(x => x.Name == "Invoke"); n.methods.Add(inv); Require(inv.ReturnType); foreach (var p in inv.Parameters) Require(p.ParameterType); }
		}

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated> by stubgen: signatures copied from the real VaM/Unity assemblies. Do not edit. </auto-generated>");
		sb.AppendLine("#pragma warning disable");
		sb.AppendLine("using System; using System.Collections; using System.Collections.Generic;");
		var tops = needs.Values.Where(n => n.def.DeclaringType == null && !n.existsInShim).ToList();
		foreach (var g in tops.GroupBy(n => n.def.Namespace))
		{
			if (g.Key != "") sb.AppendLine("namespace " + g.Key + " {");
			foreach (var n in g) Emit(sb, n);
			if (g.Key != "") sb.AppendLine("}");
		}
		File.WriteAllText(outFile, sb.ToString());
		int stubbed = needs.Values.Count(n => !n.existsInShim);
		Console.WriteLine("stubbed " + stubbed + " type(s)");
		foreach (var n in needs.Values.Where(n => n.existsInShim))
		{
			var have = shimMembers[n.def.FullName];
			foreach (var m in n.methods) if (!have.Contains(m.Name)) Console.WriteLine("MISSING MEMBER on existing shim type: " + n.def.FullName + "::" + m.Name);
			foreach (var f in n.fields) if (!have.Contains(f.Name)) Console.WriteLine("MISSING FIELD on existing shim type: " + n.def.FullName + "::" + f.Name);
		}
		foreach (var r in report.Distinct().Take(30)) Console.WriteLine("note: " + r);
		return 0;
	}

	private static IEnumerable<TypeDefinition> AllTypes(IEnumerable<TypeDefinition> ts)
	{
		foreach (var t in ts) { yield return t; foreach (var n in AllTypes(t.NestedTypes)) yield return n; }
	}

	private static Need GetNeed(TypeDefinition rd)
	{
		if (needs.TryGetValue(rd.FullName, out var n)) return n;
		n = new Need { def = rd, existsInShim = shimTypes.Contains(rd.FullName) };
		needs[rd.FullName] = n;
		if (!n.existsInShim) work.Enqueue(rd.FullName);
		return n;
	}

	private static void Require(TypeReference tr)
	{
		if (tr == null) return;
		if (tr is GenericInstanceType git) { Require(git.ElementType); foreach (var a in git.GenericArguments) Require(a); return; }
		if (tr is ArrayType at) { Require(at.ElementType); return; }
		if (tr is ByReferenceType br) { Require(br.ElementType); return; }
		if (tr is GenericParameter) return;
		if (!IsGameScope(tr.Scope)) return;
		if (realTypes.TryGetValue(tr.FullName, out var rd)) GetNeed(rd);
	}

	private static bool IsDelegate(TypeDefinition d) => d.BaseType != null && d.BaseType.FullName == "System.MulticastDelegate";

	private static string Name(TypeReference tr)
	{
		switch (tr.FullName)
		{
			case "System.Void": return "void"; case "System.Boolean": return "bool"; case "System.Int32": return "int"; case "System.Single": return "float";
			case "System.String": return "string"; case "System.Object": return "object"; case "System.Double": return "double"; case "System.Int64": return "long";
			case "System.Byte": return "byte"; case "System.UInt32": return "uint"; case "System.Int16": return "short"; case "System.UInt16": return "ushort"; case "System.SByte": return "sbyte"; case "System.UInt64": return "ulong"; case "System.Char": return "char";
		}
		if (tr is GenericParameter gp) return gp.Name;
		if (tr is ArrayType at) return Name(at.ElementType) + "[" + new string(',', at.Rank - 1) + "]";
		if (tr is ByReferenceType br) return Name(br.ElementType);
		if (tr is GenericInstanceType git)
		{
			string bn = Name(git.ElementType);
			int tick = bn.IndexOf('`'); if (tick >= 0) bn = bn.Substring(0, tick);
			return bn + "<" + string.Join(", ", git.GenericArguments.Select(Name)) + ">";
		}
		string full = tr.DeclaringType != null ? Name(tr.DeclaringType) + "." + tr.Name : (string.IsNullOrEmpty(tr.Namespace) ? "" : "global::" + tr.Namespace + ".") + tr.Name;
		if (string.IsNullOrEmpty(tr.Namespace) && tr.DeclaringType == null) full = "global::" + tr.Name;
		int t2 = full.IndexOf('`'); if (t2 >= 0) full = full.Substring(0, t2);
		return full;
	}

	private static string GenericDecl(TypeDefinition d)
	{
		var own = d.GenericParameters.Skip(d.DeclaringType?.GenericParameters.Count ?? 0).ToList();
		return own.Count == 0 ? "" : "<" + string.Join(", ", own.Select(g => g.Name)) + ">";
	}

	private static string SimpleName(TypeDefinition d) { string n = d.Name; int t = n.IndexOf('`'); return t >= 0 ? n.Substring(0, t) : n; }

	private static void Emit(StringBuilder sb, Need n)
	{
		var d = n.def;
		string nm = SimpleName(d) + GenericDecl(d);
		if (d.IsEnum)
		{
			sb.AppendLine("public enum " + SimpleName(d) + " : " + Name(d.Fields.First(f => f.Name == "value__").FieldType) + " {");
			foreach (var f in d.Fields.Where(f => f.Name != "value__")) sb.AppendLine("  " + f.Name + " = " + Convert.ToInt64(f.Constant) + ",");
			sb.AppendLine("}");
			return;
		}
		if (IsDelegate(d))
		{
			var inv = d.Methods.First(m => m.Name == "Invoke");
			sb.AppendLine("public delegate " + Name(inv.ReturnType) + " " + nm + "(" + Params(inv) + ");");
			return;
		}
		string kind = d.IsInterface ? "interface" : d.IsValueType ? "struct" : "class";
		string mods = "public " + (d.IsAbstract && d.IsSealed ? "static " : d.IsAbstract && !d.IsInterface ? "abstract " : "") + (kind == "class" && !d.IsAbstract && d.IsSealed ? "sealed " : "");
		string bases = "";
		if (kind == "class" && d.BaseType != null && d.BaseType.FullName != "System.Object") bases = " : " + Name(d.BaseType);
		sb.AppendLine(mods + "partial " + kind + " " + nm + bases + " {");
		var props = new Dictionary<string, PropertyDefinition>();
		var emittedProps = new HashSet<string>();
		bool hasCtor = false;
		foreach (var m in n.methods.OrderBy(x => x.Name))
		{
			if (m.IsConstructor && !m.IsStatic) { hasCtor = true; sb.AppendLine("  public " + SimpleName(d) + "(" + Params(m) + ") " + (d.BaseType != null && !d.IsValueType && NeedsBase(d) ? ": base(" + BaseArgs(d) + ") " : "") + "{}"); continue; }
			if (m.IsStatic && m.IsConstructor) continue;
			var prop = d.Properties.FirstOrDefault(p => (p.GetMethod != null && p.GetMethod.FullName == m.FullName) || (p.SetMethod != null && p.SetMethod.FullName == m.FullName));
			if (prop != null)
			{
				if (!emittedProps.Add(prop.Name)) continue;
				var acc = (n.methods.Any(x => prop.GetMethod != null && x.FullName == prop.GetMethod.FullName) ? "get; " : "") + (n.methods.Any(x => prop.SetMethod != null && x.FullName == prop.SetMethod.FullName) ? "set; " : "");
				acc = "get; set; ";
				string pinit = (!prop.PropertyType.IsValueType && prop.PropertyType.Name.Contains("Event") && !(prop.PropertyType is GenericParameter)) ? " = new " + Name(prop.PropertyType) + "();" : "";
				sb.AppendLine("  public " + (m.IsStatic ? "static " : "") + Name(prop.PropertyType) + " " + prop.Name + " { " + acc + "}" + pinit);
				continue;
			}
			if (d.IsInterface) { sb.AppendLine("  " + Name(m.ReturnType) + " " + m.Name + GenericM(m) + "(" + Params(m) + ");"); continue; }
			string outs = string.Concat(m.Parameters.Where(p => p.IsOut).Select(p => (string.IsNullOrEmpty(p.Name) ? "p" + p.Index : p.Name) + " = default; "));
			string body = m.ReturnType.FullName == "System.Void" ? "{ " + outs + "}" : "{ " + outs + "return " + DefaultExpr(m) + "; }";
			string ov = m.IsVirtual && !m.IsNewSlot && d.BaseType != null && !m.IsAbstract && m.Name != "Finalize" ? "override " : "";
			if (m.IsVirtual && m.IsNewSlot && !d.IsSealed) ov = "virtual ";
			sb.AppendLine("  public " + (m.IsStatic ? "static " : "") + ov + Name(m.ReturnType) + " " + m.Name + GenericM(m) + "(" + Params(m) + ") " + body);
		}
		foreach (var f in n.fields.OrderBy(x => x.Name))
		{
			if (d.IsEnum) continue;
			sb.AppendLine("  public " + (f.IsStatic ? "static " : "") + (f.IsLiteral ? "" : "") + Name(f.FieldType) + " " + f.Name + ";");
		}
		if (kind == "class" && !(d.IsAbstract && d.IsSealed) && !n.methods.Any(x => x.IsConstructor && !x.IsStatic && x.Parameters.Count == 0)) sb.AppendLine("  public " + SimpleName(d) + "() {}");
		foreach (var nt in d.NestedTypes)
			if (needs.TryGetValue(nt.FullName, out var nn) && !nn.existsInShim) Emit(sb, nn);
		sb.AppendLine("}");
	}

	private static string DefaultExpr(MethodDefinition m)
	{
		var rt = m.ReturnType;
		if (m.Name == "LoadImage") return "true";
		if (rt.FullName == "System.String") return "\"\"";
		if (rt is ArrayType at) return "new " + Name(at.ElementType) + "[0]";
		if (rt is GenericInstanceType git)
		{
			string en = git.ElementType.FullName;
			if (en == "System.Collections.Generic.List`1" || en == "System.Collections.Generic.Dictionary`2" || en == "System.Collections.Generic.HashSet`1") return "new " + Name(rt) + "()";
			if (en == "System.Collections.Generic.IEnumerable`1" || en == "System.Collections.Generic.ICollection`1" || en == "System.Collections.Generic.IList`1") return "new " + Name(git.GenericArguments[0]) + "[0]";
		}
		return "default";
	}

	private static bool NeedsBase(TypeDefinition d) => false;
	private static string BaseArgs(TypeDefinition d) => "";
	private static string GenericM(MethodDefinition m) => m.GenericParameters.Count == 0 ? "" : "<" + string.Join(", ", m.GenericParameters.Select(g => g.Name)) + ">";

	private static string Params(MethodDefinition m)
	{
		var parts = new List<string>();
		foreach (var p in m.Parameters)
		{
			string mod = p.ParameterType is ByReferenceType ? (p.IsOut ? "out " : "ref ") : "";
			string pn = p.Name; if (string.IsNullOrEmpty(pn)) pn = "p" + p.Index;
			if (pn == "object" || pn == "string" || pn == "params" || pn == "base" || pn == "event" || pn == "ref" || pn == "out" || pn == "in" || pn == "is" || pn == "this" || pn == "lock" || pn == "operator") pn = "@" + pn;
			string def = "";
			if (p.IsOptional) def = " = default";
			parts.Add(mod + Name(p.ParameterType) + " " + pn + def);
		}
		return string.Join(", ", parts);
	}
}
